package xeMt;

import org.testng.annotations.Test;

import utils.Browsers;
import utils.General;
import xemt_UI.WhyXePage;

import java.lang.reflect.Array;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'naga' at '9/12/16 3:42 PM' with Gradle 2.14.1
 *
 * @author naga, @date 9/12/16 3:42 PM
 */

// C5240 Verify Xe Money transfer web page is navigating properly or not 
//C5254	Verify Xe Money transfer webpage navigating properly
//C5234	Click on Personal Link and check the webpage navigating properly or not
//C5250	Click on Personal Link and check the webpage navigating properly or not
//C5222 check  the content under " Why Xe" tab in personal function for 5 regions which are US,CA,UK,AU,NZ. The content under Why Xe is  different for 5 regioons
//C5223	check the content under " How it works" tab in personal function for 5 regions which are US,CA,UK,AU,NZ
// C5224	check the content under " Currencies" tab in personal function for 5 regions which are US,CA,UK,AU,NZ

public class ID0001_XeMtPersonal {

	private String baseUrl;
	private WebDriver driver;
	private WhyXePage home;
	private General general;

	@Parameters({ "BaseUrl", "browser" })
	@BeforeClass
	public void BaseUrl(@Optional("http://gamma.xe.com/") String url, @Optional("firefoxLocal") String browser)
			throws MalformedURLException, InterruptedException {
		driver = Browsers.getDriver(browser);
		general = PageFactory.initElements(driver, General.class);
		home = PageFactory.initElements(driver, WhyXePage.class);
		baseUrl = url;
	}

	@Test
	public void a_redirectToXeMt() throws InterruptedException {

		driver.get(baseUrl);
		general.wait10sec();
		driver.get(baseUrl + "/xemoneytransfer/");
		general.wait10sec();
		driver.findElement(By.cssSelector(".active")).click();
		//home.personalbtn.click();
		driver.get(baseUrl + "/xemoneytransfer/");
		// Check the content for Nz
		driver.get(baseUrl + "/xemoneytransfer/" + "/nz/");
		String text = home.text.getText();
		Assert.assertEquals(text, "XE Money Transfer - connecting the world through currency exchange."+"\n"+"XE Money Transfer is the quick, easy, and secure way to transfer money around the globe. With competitive exchange rates you can book international payments 24/7."+"\n"+"Every year, over 33,000 people and 2,000 businesses trust us to make global payments, send funds to family, pay international businesses, and buy foreign real estate. At XE, we're not just passionate about saving you money, we're proud of our exceptional service as we connect the world through currency exchange.");
		String txt05 = home.sixItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt05, "Great rates");
		checkContent();
		// Check the content for AU
		driver.get(baseUrl + "/xemoneytransfer" + "/au/");
		String text4 = home.text.getText();
		Assert.assertEquals(text4, "Don't let the banks cash in on your international money transfers" + "\n"+"XE Money Transfer is the quick, easy, and secure way to transfer money around the globe. With competitive exchange rates you can book international payments 24/7."+"\n"+"Every year, over 33,000 people and 2,000 businesses trust us to make global payments, send funds to family, pay international businesses, and buy foreign real estate. At XE, we're not just passionate about saving you money, we're proud of our exceptional service as we connect the world through currency exchange.");
		String txt07 = home.sixItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt07, "Great rates");
		checkContent();
		// check the content for ca
		driver.get(baseUrl + "/xemoneytransfer/" + "/ca/");
		String text3 = home.text.getText();
		Assert.assertEquals(text3, "XE Money Transfer - connecting the world through currency exchange."+"\n"+"XE Money Transfer is the quick, easy, and secure way to transfer money around the globe. With competitive exchange rates you can book international payments 24/7."+"\n"+"Every year, over 33,000 people and 2,000 businesses trust us to make global payments, send funds to family, pay international businesses, and buy foreign real estate. At XE, we're not just passionate about saving you money, we're proud of our exceptional service as we connect the world through currency exchange.");
		String txt06 = home.sixItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt06, "Great rates");
		checkContent();
		// check the content for US
		driver.get(baseUrl + "/xemoneytransfer/" + "/us/");
		String text2 = home.text.getText();
		Assert.assertEquals(text2, "Don't let the banks cash in on your international money transfers" + "\n"+"XE Money Transfer is the quick, easy, and secure way to transfer money around the globe. With competitive exchange rates you can book international payments 24/7."+"\n"+"Every year, over 33,000 people and 2,000 businesses trust us to make global payments, send funds to family, pay international businesses, and buy foreign real estate. At XE, we're not just passionate about saving you money, we're proud of our exceptional service as we connect the world through currency exchange.");
		String txt08 = home.sixItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt08, "Bank beating");
		checkContent();
		// check the content for UK
		driver.get(baseUrl + "/xemoneytransfer/" + "/uk/");
		String text5 = home.text.getText();
		Assert.assertEquals(text5, "Don't let the banks cash in on your international money transfers" +"\n"+"XE Money Transfer is the quick, easy, and secure way to transfer money around the globe. With competitive exchange rates you can book international payments 24/7."+"\n"+"Every year, over 33,000 people and 2,000 businesses trust us to make global payments, send funds to family, pay international businesses, and buy foreign real estate. At XE, we're not just passionate about saving you money, we're proud of our exceptional service as we connect the world through currency exchange.");
		String txt09 = home.sixItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt09, "Bank beating");
		checkContent();
		// Check the content for Nz
		driver.get(baseUrl + "/xemoneytransfer/" + "/nz/" + "#howitworks");

		checkContent1();
		// Check the content for AU
		driver.get(baseUrl + "/xemoneytransfer/" + "/au/" + "#howitworks");

		checkContent1();
		// check the content for ca
		driver.get(baseUrl + "/xemoneytransfer/" + "/ca/" + "#howitworks");

		checkContent1();
		// check the content for US
		driver.get(baseUrl + "/xemoneytransfer/" + "/us/" + "#howitworks");

		checkContent1();
		// check the content for UK
		driver.get(baseUrl + "/xemoneytransfer/" + "/uk/" + "#howitworks");

		checkContent1();
		String text9 = home.LargeTransferSection_UI.getText();
		Assert.assertEquals(text9,"Online Money Transfers" + "\n"+"We're proud of the fact that we’re one of the quickest and easiest ways to send money around the world."+"\n"+"Benefits include:"+"\n"+"Fee free transfers."+"\n"+"Highly competitive exchange rates." + "\n"+"Send money, and track payments 24/7 via your mobile, tablet or PC." + "\n"+"Norton security trusted by 97 of the World's 100 largest banks so you’re fully protected online."+"\n"+"Used to transfer over $150 billion by customers in 127 countries.");
		// Check currencies buttton
		// Check the content for Nz
		driver.get(baseUrl + "/xemoneytransfer/" + "/nz/" + "#currencies");
		checkContent2();
		String text13 = home.TabPane_UI.get(8).getText();
		Assert.assertEquals(text13,"We trade in 60 world currencies and you can transfer money to over 170 countries.");
		checkContent3();
		// Check the content for AU
		driver.get(baseUrl + "/xemoneytransfer/" + "/au/" + "#currencies");
		checkContent2();
		String text14 = home.TabPane_UI.get(8).getText();
		Assert.assertEquals(text14,"We trade in 60 world currencies and you can transfer money to over 170 countries.");
		checkContent3();
		// check the content for ca
		driver.get(baseUrl + "/xemoneytransfer/" + "/ca/" + "#currencies");
		checkContent2();
		String text15 = home.TabPane_UI.get(8).getText();
		Assert.assertEquals(text15,"We trade in 60 world currencies and you can transfer money to over 170 countries.");
		checkContent4();
		// check the content for US
		driver.get(baseUrl + "/xemoneytransfer/" + "/us/" + "#currencies");
		checkContent2();
		String text16 = home.TabPane_UI.get(10).getText();
		Assert.assertEquals(text16,"We trade in 60 world currencies and you can transfer money to over 170 countries.");
		checkContent4();
		// check the content for UK
		driver.get(baseUrl + "/xemoneytransfer/" + "/uk/" + "#currencies");
		Thread.sleep(1000);
		home.tabsList_UI.get(2).findElement(By.cssSelector("a")).click();
		List<WebElement> h1 = driver.findElements(By.cssSelector(".tabPane h2"));
		String text12 = h1.get(3).getText();
		Assert.assertEquals(text12, "Your money to the currency you need");
		String text17 = home.TabPane_UI.get(10).getText();
		Assert.assertEquals(text17,"We trade in 60 world currencies and you can transfer money to over 170 countries.");
		checkContent5();
	}

	@AfterClass

	public void close() {
		driver.close();
	}

	// content for Why Xe

	private void checkContent() {

		String txt06 = home.sixItems.get(1).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt06, "No fees");
		String txt07 = home.sixItems.get(2).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt07, "Fast & easy");
		String txt08 = home.sixItems.get(3).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt08, "With care");
		String txt09 = home.sixItems.get(4).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt09, "Secure");
		String txt10 = home.sixItems.get(5).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt10, "Free tools");
		String txt11 = home.JoinNowmakeTransfer_UI.getText();
		Assert.assertEquals(txt11, "Join now and see how much you can save:" + "\n" + "Free Personal Account" + "\n"+ "Free Business Account");
		String txt12 = home.FeefreePromo_UI.getText();
		Assert.assertEquals(txt12,"FREE" + "\n" + "Enjoy FREE transfers with XE!" + "\n" + "Save time and money." + "\n"+ "Simply sign up today for fee free transfers AND great exchange rates." + "\n"+ "Existing customers log in now to make a transfer and benefit.");
	}

	// Content - How it works
	private void checkContent1() throws InterruptedException  {
		Thread.sleep(1000);
		general.waitElementIsPresented(home.modifiedheading_UI.get(1));

		String text8 = home.modifiedheading_UI.get(1).getText();
		Assert.assertEquals(text8, "Fast and really easy to use");
		String txt1 = home.fourItems.get(0).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt1, "To get a free quote choose the currencies and amount you want to send.");
		String txt2 = home.fourItems.get(1).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt2, "Tell us where you'd like us to send your money to.");
		String txt3 = home.fourItems.get(2).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt3, "Confirm your order and send your money to us.");
		String txt4 = home.fourItems.get(3).findElement(By.cssSelector(".desc")).getText();
		Assert.assertEquals(txt4, "Sit back and relax as we do the rest and send your money around the world.");
		String text11 = home.joinNow_UI.get(1).getText();
		Assert.assertEquals(text11, "See how fast and easy your money transfer can be:");

	}

	private void checkContent2() throws InterruptedException {

		Thread.sleep(1000);
		home.tabsList_UI.get(2).findElement(By.cssSelector("a")).click();
		List<WebElement> h1 = driver.findElements(By.cssSelector(".tabPane h2"));
		String text12 = h1.get(2).getText();
		Assert.assertEquals(text12, "Your money to the currency you need");

	}

	private void checkContent3() {
		String text8 = home.region_UI.get(14).getText();
		Assert.assertEquals(text8, "AED Emirati Dirham");
		String text9 = home.region_UI.get(21).getText();
		Assert.assertEquals(text9, "AUD Australian Dollar");
		String text10 = home.region_UI.get(0).getText();
		Assert.assertEquals(text10, "CAD Canadian Dollar");
		String text11 = home.region_UI.get(4).getText();
		Assert.assertEquals(text11, "CHF Swiss Franc");
		String text12 = home.region_UI.get(5).getText();
		Assert.assertEquals(text12, "CZK Czech Koruna");
		String text13 = home.region_UI.get(6).getText();
		Assert.assertEquals(text13, "DKK Danish Krone");
		String text14 = home.region_UI.get(7).getText();
		Assert.assertEquals(text14, "EUR Euro");
		String text15 = home.region_UI.get(22).getText();
		Assert.assertEquals(text15, "FJD Fijian Dollar");
		String text16 = home.region_UI.get(8).getText();
		Assert.assertEquals(text16, "GBP British Pound");
		String text17 = home.region_UI.get(15).getText();
		Assert.assertEquals(text17, "HKD Hong Kong Dollar");
		String text18 = home.region_UI.get(9).getText();
		Assert.assertEquals(text18, "HUF Hungarian Forint");
		String text19 = home.region_UI.get(16).getText();
		Assert.assertEquals(text19, "INR Indian Rupee");
		String text20 = home.region_UI.get(17).getText();
		Assert.assertEquals(text20, "JPY Japanese Yen");
		String text21 = home.region_UI.get(1).getText();
		Assert.assertEquals(text21, "MXN Mexican Peso");
		String text22 = home.region_UI.get(10).getText();
		Assert.assertEquals(text22, "NOK Norwegian Krone");
		String text23 = home.region_UI.get(23).getText();
		Assert.assertEquals(text23, "NZD New Zealand Dollar");
		String text24 = home.region_UI.get(24).getText();
		Assert.assertEquals(text24, "PGK Papua New Guinean Kina");
		String text25 = home.region_UI.get(18).getText();
		Assert.assertEquals(text25, "PHP Philippine Peso");
		String text26 = home.region_UI.get(11).getText();
		Assert.assertEquals(text26, "PLN Polish Zloty");
		String text27 = home.region_UI.get(25).getText();
		Assert.assertEquals(text27, "SBD Solomon Islander Dollar");
		String text28 = home.region_UI.get(12).getText();
		Assert.assertEquals(text28, "SEK Swedish Krona");
		String text29 = home.region_UI.get(19).getText();
		Assert.assertEquals(text29, "SGD Singapore Dollar");
		String text30 = home.region_UI.get(20).getText();
		Assert.assertEquals(text30, "THB Thai Baht");
		String text31 = home.region_UI.get(26).getText();
		Assert.assertEquals(text31, "TOP Tongan Pa'anga");
		String text32 = home.region_UI.get(2).getText();
		Assert.assertEquals(text32, "USD US Dollar");
		String text33 = home.region_UI.get(3).getText();
		Assert.assertEquals(text33, "VUV Ni-Vanuatu Vatu");
		String text34 = home.region_UI.get(27).getText();
		Assert.assertEquals(text34, "WST Samoan Tala");
		String text35 = home.region_UI.get(28).getText();
		Assert.assertEquals(text35, "XPF CFP Franc");
		String text36 = home.region_UI.get(13).getText();
		Assert.assertEquals(text36, "ZAR South African Rand");
	}

	private void checkContent4() {
		String text1 = home.region_UI.get(0).getText();
		Assert.assertEquals(text1, "BBD Barbadian or Bajan Dollar*");
		String text2 = home.region_UI.get(1).getText();
		Assert.assertEquals(text2, "BSD Bahamian Dollar*");
		String text3 = home.region_UI.get(2).getText();
		Assert.assertEquals(text3, "CAD Canadian Dollar");
		String text11 = home.region_UI.get(3).getText();
		Assert.assertEquals(text11, "JMD Jamaican Dollar*");
		String text12 = home.region_UI.get(4).getText();
		Assert.assertEquals(text12, "MXN Mexican Peso");
		String text13 = home.region_UI.get(5).getText();
		Assert.assertEquals(text13, "USD US Dollar");
		String text14 = home.region_UI.get(6).getText();
		Assert.assertEquals(text14, "XCD East Caribbean Dollar*");
		String text15 = home.region_UI.get(7).getText();
		Assert.assertEquals(text15, "BZD Belizean Dollar*");
		String text16 = home.region_UI.get(8).getText();
		Assert.assertEquals(text16, "TTD Trinidadian Dollar");
		String text17 = home.region_UI.get(9).getText();
		Assert.assertEquals(text17, "BGN Bulgarian Lev");
		String text18 = home.region_UI.get(10).getText();
		Assert.assertEquals(text18, "CHF Swiss Franc");
		String text19 = home.region_UI.get(11).getText();
		Assert.assertEquals(text19, "CZK Czech Koruna");
		String text20 = home.region_UI.get(12).getText();
		Assert.assertEquals(text20, "DKK Danish Krone");
		String text21 = home.region_UI.get(13).getText();
		Assert.assertEquals(text21, "EUR Euro");
		String text22 = home.region_UI.get(14).getText();
		Assert.assertEquals(text22, "GBP British Pound");
		String text23 = home.region_UI.get(15).getText();
		Assert.assertEquals(text23, "HRK Croatian Kuna");
		String text24 = home.region_UI.get(16).getText();
		Assert.assertEquals(text24, "HUF Hungarian Forint");
		String text25 = home.region_UI.get(17).getText();
		Assert.assertEquals(text25, "ILS Israeli Shekel");
		String text26 = home.region_UI.get(18).getText();
		Assert.assertEquals(text26, "NOK Norwegian Krone");
		String text27 = home.region_UI.get(19).getText();
		Assert.assertEquals(text27, "PLN Polish Zloty");
		String text28 = home.region_UI.get(20).getText();
		Assert.assertEquals(text28, "RON Romanian Leu");
		String text29 = home.region_UI.get(21).getText();
		Assert.assertEquals(text29, "RSD Serbian Dinar");
		String text30 = home.region_UI.get(22).getText();
		Assert.assertEquals(text30, "SEK Swedish Krona");
		String text31 = home.region_UI.get(23).getText();
		Assert.assertEquals(text31, "TRY Turkish Lira");
		String text32 = home.region_UI.get(24).getText();
		Assert.assertEquals(text32, "BWP Botswana Pula");
		String text33 = home.region_UI.get(25).getText();
		Assert.assertEquals(text33, "GHS Ghanaian Cedi*");
		String text34 = home.region_UI.get(26).getText();
		Assert.assertEquals(text34, "KES Kenyan Shilling");
		String text35 = home.region_UI.get(27).getText();
		Assert.assertEquals(text35, "LSL Basotho Loti");
		String text36 = home.region_UI.get(28).getText();
		Assert.assertEquals(text36, "MUR Mauritian Rupee");
		String text37 = home.region_UI.get(29).getText();
		Assert.assertEquals(text37, "MWK Malawian Kwacha*");
		String text38 = home.region_UI.get(30).getText();
		Assert.assertEquals(text38, "SZL Swazi Lilangeni");
		String text39 = home.region_UI.get(31).getText();
		Assert.assertEquals(text39, "TND Tunisian Dinar");
		String text40 = home.region_UI.get(32).getText();
		Assert.assertEquals(text40, "ZAR South African Rand");
		String text41 = home.region_UI.get(33).getText();
		Assert.assertEquals(text41, "ZMW Zambian Kwacha*");
		String text42 = home.region_UI.get(34).getText();
		Assert.assertEquals(text42, "AED Emirati Dirham");
		String text43 = home.region_UI.get(35).getText();
		Assert.assertEquals(text43, "BHD Bahraini Dinar");
		String text44 = home.region_UI.get(36).getText();
		Assert.assertEquals(text44, "HKD Hong Kong Dollar");
		String text45 = home.region_UI.get(37).getText();
		Assert.assertEquals(text45, "JOD Jordanian Dinar");
		String text46 = home.region_UI.get(38).getText();
		Assert.assertEquals(text46, "JPY Japanese Yen");
		String text47 = home.region_UI.get(39).getText();
		Assert.assertEquals(text47, "KWD Kuwaiti Dinar");
		String text48 = home.region_UI.get(40).getText();
		Assert.assertEquals(text48, "LKR Sri Lankan Rupee*");
		String text49 = home.region_UI.get(41).getText();
		Assert.assertEquals(text49, "OMR Omani Rial");
		String text50 = home.region_UI.get(42).getText();
		Assert.assertEquals(text50, "PHP Philippine Peso");
		String text51 = home.region_UI.get(43).getText();
		Assert.assertEquals(text51, "PKR Pakistani Rupee*");
		String text52 = home.region_UI.get(44).getText();
		Assert.assertEquals(text52, "QAR Qatari Riyal");
		String text53 = home.region_UI.get(45).getText();
		Assert.assertEquals(text53, "SAR Saudi Arabian Riyal");
		String text54 = home.region_UI.get(46).getText();
		Assert.assertEquals(text54, "SGD Singapore Dollar");
		String text55 = home.region_UI.get(47).getText();
		Assert.assertEquals(text55, "THB Thai Baht");
		String text56 = home.region_UI.get(48).getText();
		Assert.assertEquals(text56, "AUD Australian Dollar");
		String text57 = home.region_UI.get(49).getText();
		Assert.assertEquals(text57, "FJD Fijian Dollar");
		String text58 = home.region_UI.get(50).getText();
		Assert.assertEquals(text58, "NZD New Zealand Dollar");
	}

	private void checkContent5() {
		String text1 = home.region_UI.get(0).getText();
		Assert.assertEquals(text1, "CAD Canadian Dollar");
		String text2 = home.region_UI.get(1).getText();
		Assert.assertEquals(text2, "MXN Mexican Peso");
		String text3 = home.region_UI.get(2).getText();
		Assert.assertEquals(text3, "USD US Dollar");
		String text11 = home.region_UI.get(3).getText();
		Assert.assertEquals(text11, "BGN Bulgarian Lev");
		String text12 = home.region_UI.get(4).getText();
		Assert.assertEquals(text12, "CHF Swiss Franc");
		String text13 = home.region_UI.get(5).getText();
		Assert.assertEquals(text13, "CZK Czech Koruna");
		String text14 = home.region_UI.get(6).getText();
		Assert.assertEquals(text14, "DKK Danish Krone");
		String text15 = home.region_UI.get(7).getText();
		Assert.assertEquals(text15, "EUR Euro");
		String text16 = home.region_UI.get(8).getText();
		Assert.assertEquals(text16, "GBP British Pound");
		String text17 = home.region_UI.get(9).getText();
		Assert.assertEquals(text17, "HRK Croatian Kuna");
		String text18 = home.region_UI.get(10).getText();
		Assert.assertEquals(text18, "HUF Hungarian Forint");
		String text19 = home.region_UI.get(11).getText();
		Assert.assertEquals(text19, "ILS Israeli Shekel");
		String text20 = home.region_UI.get(12).getText();
		Assert.assertEquals(text20, "NOK Norwegian Krone");
		String text21 = home.region_UI.get(13).getText();
		Assert.assertEquals(text21, "PLN Polish Zloty");
		String text22 = home.region_UI.get(14).getText();
		Assert.assertEquals(text22, "RON Romanian Leu");
		String text23 = home.region_UI.get(15).getText();
		Assert.assertEquals(text23, "RSD Serbian Dinar");
		String text24 = home.region_UI.get(16).getText();
		Assert.assertEquals(text24, "SEK Swedish Krona");
		String text25 = home.region_UI.get(17).getText();
		Assert.assertEquals(text25, "TRY Turkish Lira");
		String text26 = home.region_UI.get(18).getText();
		Assert.assertEquals(text26, "BWP Botswana Pula");
		String text27 = home.region_UI.get(19).getText();
		Assert.assertEquals(text27, "KES Kenyan Shilling");
		String text28 = home.region_UI.get(20).getText();
		Assert.assertEquals(text28, "LSL Basotho Loti");
		String text29 = home.region_UI.get(21).getText();
		Assert.assertEquals(text29, "MUR Mauritian Rupee");
		String text30 = home.region_UI.get(22).getText();
		Assert.assertEquals(text30, "SZL Swazi Lilangeni");
		String text31 = home.region_UI.get(23).getText();
		Assert.assertEquals(text31, "TND Tunisian Dinar");
		String text32 = home.region_UI.get(24).getText();
		Assert.assertEquals(text32, "ZAR South African Rand");
		String text33 = home.region_UI.get(25).getText();
		Assert.assertEquals(text33, "AED Emirati Dirham");
		String text34 = home.region_UI.get(26).getText();
		Assert.assertEquals(text34, "BHD Bahraini Dinar");
		String text35 = home.region_UI.get(27).getText();
		Assert.assertEquals(text35, "HKD Hong Kong Dollar");
		String text36 = home.region_UI.get(28).getText();
		Assert.assertEquals(text36, "JOD Jordanian Dinar");
		String text37 = home.region_UI.get(29).getText();
		Assert.assertEquals(text37, "JPY Japanese Yen");
		String text38 = home.region_UI.get(30).getText();
		Assert.assertEquals(text38, "KWD Kuwaiti Dinar");
		String text39 = home.region_UI.get(31).getText();
		Assert.assertEquals(text39, "OMR Omani Rial");
		String text40 = home.region_UI.get(32).getText();
		Assert.assertEquals(text40, "PHP Philippine Peso");
		String text41 = home.region_UI.get(33).getText();
		Assert.assertEquals(text41, "QAR Qatari Riyal");
		String text42 = home.region_UI.get(34).getText();
		Assert.assertEquals(text42, "SAR Saudi Arabian Riyal");
		String text43 = home.region_UI.get(35).getText();
		Assert.assertEquals(text43, "SGD Singapore Dollar");
		String text44 = home.region_UI.get(36).getText();
		Assert.assertEquals(text44, "THB Thai Baht");
		String text45 = home.region_UI.get(37).getText();
		Assert.assertEquals(text45, "AUD Australian Dollar");
		String text46 = home.region_UI.get(38).getText();
		Assert.assertEquals(text46, "NZD New Zealand Dollar");
	}
}
