package XeMt;

import org.testng.annotations.Test;
import org.testng.AssertJUnit;
import org.testng.annotations.Test;
import org.testng.AssertJUnit;
import org.testng.annotations.Test;

import xemt_UI.WhyXePage;

import java.lang.reflect.Array;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'naga' at '9/12/16 3:42 PM' with Gradle 2.14.1
 *
 * @author naga, @date 9/12/16 3:42 PM
 */



// C5240 Verify Xe Money transfer web page is navigating properly or not 
//C5254	Verify Xe Money transfer webpage navigating properly



public class ID0005_XemtBusinessLastTabs {
	
	private String baseUrl;
	private FirefoxDriver driver;
	private WhyXePage home;
	
	
	@Parameters({"BaseUrl","browser"})
    @BeforeClass
    public void BaseUrl(@Optional("http://mlo04.xe.com") String url, @Optional("firefox")String browser) throws MalformedURLException, InterruptedException {	
		driver = new FirefoxDriver();
		home =  PageFactory.initElements(driver, WhyXePage.class);
		baseUrl = "http://gamma.xe.com/";
		
		
	}
         @Test
         public void a_redirectToXeMt() {
    		
        	 //	C7608	XE Money Transfer - Last 3 tabs
        	 
   		  driver.get(baseUrl);
   		  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
   		  driver.get(baseUrl+"/xemoneytransfer/");
   		  driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
   		  driver.findElement(By.cssSelector(".active")).click();
   		  driver.get(baseUrl+"xemoneytransfer/business/");
		  //content Trusted brand
   		  List<WebElement> p3 = driver.findElements(By.cssSelector(".tabPane p")) ;
		  String text4 =  p3.get(8).getText();
		  AssertJUnit.assertEquals(text4,"Over the past 20 years, we've earned the trust of millions of people worldwide through our transparent exchange rates and free currency tools. With XE Money Transfers, we continue to build this trust by offering a service that exemplifies respect for customers.");
		  List<WebElement> p4 = driver.findElements(By.cssSelector(".tabPane p")) ;
		  String text5 =  p4.get(8).getText();
		  AssertJUnit.assertEquals(text5,"Trust us for your next money transfer. Join now:");
		  //Content Secure and reliable
		  List<WebElement> p1 = driver.findElements(By.cssSelector(".tabPane h1")) ;
 		  String text1 =  p1.get(5).getText();
 		  AssertJUnit.assertEquals(text1,"Your security is our priority.");
 		  List<WebElement> p2 = driver.findElements(By.cssSelector(".featureIcons.security.clearfix")) ;
 		  String text2 =  p2.get(0).getText();
 		  AssertJUnit.assertEquals(text2,"Secure We take the greatest care in ensuring the security of XE Money Transfer. That's why we use Norton security – 97 of the world's 100 largest banks and over 93% of Fortune 500 companies use Norton. In addition, Norton secures more than one million Web servers worldwide.");
 		  String text3 =  p2.get(1).getText();
 		  AssertJUnit.assertEquals(text3,"Reliable With XE Money Transfer, you get payment tracking every step of the way. We'll keep you up to date with your transaction via SMS and email. If you choose, we can inform your recipients when your funds are on their way.");
 		  String text6 =  p2.get(1).getText();
 		  AssertJUnit.assertEquals(text6,"Regulated We take our legal responsibilities very seriously. Where required, our provider has regulatory approval in every country that we operate in including FinCen in the USA, the Financial Conduct Authority in the UK, ASIC in Australia and the FMA in New Zealand.");
 		  String text7 =  p2.get(1).getText();
 		  AssertJUnit.assertEquals(text7,"Peace of Mind In 2015, XE became part of Euronet Worldwide, Inc. (NASDAQ: EEFT), recognized leaders in providing global financial services. Last year, our group transacted over $11 billion for 112,000 clients in 117 countries.");          
 		  List<WebElement> p5 = driver.findElements(By.cssSelector(".tabPane p")) ;
 		  String text8 =  p5.get(14).getText();
 		  AssertJUnit.assertEquals(text8,"Trust us for your next money transfer. Join now:");
		   
         }
}