/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'naga' at '9/12/16 3:42 PM' with Gradle 2.14.1
 *
 * @author naga, @date 9/12/16 3:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
