package try1;

import org.testng.annotations.Test;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.net.MalformedURLException;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'naga' at '9/12/16 3:42 PM' with Gradle 2.14.1
 *
 * @author naga, @date 9/12/16 3:42 PM
 */
public class FirstTryTest {
	
	private String baseUrl;
	
	
	@Parameters({"BaseUrl","browser"})
    @BeforeClass
    public void BaseUrl(@Optional("https://xecd-dev.xe.com/") String url, @Optional("firefoxLocal")String browser   ) throws MalformedURLException, InterruptedException {
		
		FirefoxDriver driver = new FirefoxDriver();
		baseUrl = "http://beta.xe.com/?";
		driver.get(baseUrl);
		Thread.sleep(5000);
		
		
    }
	
	
	
    @Test 
    public void testSomeLibraryMethod() {
       
        
    }
    
    
    
}
