package xemt_UI;


import java.util.List;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.Select;


/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'naga' at '9/12/16 3:42 PM' with Gradle 2.14.1
 *
 * @author naga, @date 9/12/16 3:42 PM
 */


public class WhyXePage {

	 public WebDriver driver;
	    
	public WhyXePage(WebDriver driver) {
	        this.driver = driver;
	}
	
	  //Personal
	    @FindBy(css =".active")
        public WebElement personalbtn;
   
   
     // inline six items
	    @FindBy(css = ".inline.sixItems li")
	    public List<WebElement> sixItems;
	    
	    
	    	    
	//inline four items
      @FindBy(css = ".inline.fourItems li")
	  public List<WebElement> fourItems;
      
      
      @FindBy(css = ".tabPane h1")
	  public List<WebElement> heading_UI;
   
        
	
	//main text on a page
      @FindBy(css = ".whyXEMainContent")
	  public WebElement text;
      
     // tabs li 
      @FindBy(css = ".tabs li")
	   public List<WebElement> tabsList_UI;
		
     //Large Transfre Section
      @FindBy(css = ".largeTransferSection")
	   public WebElement LargeTransferSection_UI;
      
     // Tabs Pane
      @FindBy(css = ".tabPane p")
	   public List<WebElement> TabPane_UI;
      
      // Join Now Make Transfer
      @FindBy(css = ".joinNow.makeTransfer")
	   public WebElement JoinNowmakeTransfer_UI;
      
      // Fee Free Promo
      @FindBy(css = ".feeFree-promo")
	   public WebElement FeefreePromo_UI;
      // JoIn NOw
      @FindBy(css = ".joinNow p")
	   public List<WebElement> joinNow_UI;
      // Region
      @FindBy(css = ".region li")
	   public List<WebElement> region_UI;
}

	



